name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # add in secrets 
        password: ${{ secrets.DOCKER_PASSWORD }}    # add in secrets 

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: your-dockerhub-username/your-repo-name:latest   
        #make repository and change the name of repo above. 

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}

# https://github.com/marketplace/actions/build-and-push-docker-image-to-docker-hub
